### ISSUE TITLE
File.parseURI returns object with `search` field, should be `query` field.

### ISSUE THREAD

**Issue by Mark-Simulacrum** [MiguelCastillo/amd-resolver#13]
From what I have found on the internet, `?=testing=foo` is the query string, not the search string.

**Comment by MiguelCastillo** [comment]
Yeah query and search are the same thing, right?

**Comment by Mark-Simulacrum** [comment]
Perhaps - I haven't worked much with URI/URL parsing before. It seems odd to call it the search string, since in some/many cases it has nothing to do with search. Matter of opinion though, I guess.

**Comment by MiguelCastillo** [comment]
As far as my opinion goes, it is more a matter of what the browser implements in `window.location`, which is `search`.

**Comment by Mark-Simulacrum** [comment]
I did not know that `window.location` had `search` and not `query`. I see why we use `search` now.

Thank you for explaining.

**Comment by MiguelCastillo** [comment]
of course! :)
