### ISSUE TITLE
File.parseURI throws Error on passing "" with text `Must provide a string to parse`

### ISSUE THREAD

**Issue by Mark-Simulacrum** [MiguelCastillo/amd-resolver#15]
I think we should change the error type from `Error` to `TypeError` if we only accept strings, and a non-string object was passed. It also seems odd that on a string value ("") we throw that the caller should call with a string.

We check for a string value using `!value`, while we should probably be doing a `instanceof` comparison.

**Comment by Mark-Simulacrum** [comment]
(the `instanceof` being necessary only if we truly care that it is a string value).

**Comment by MiguelCastillo** [comment]
Yeah that's a good catch.  We should change the check to be `typeof(....) === 'string'` and throw a `TypeError`.

**Comment by Mark-Simulacrum** [comment]
Do we still want to throw on an empty string though? If we do, then we should probably do something like this: `... !== "" && typeof(...) === 'string'`.

**Comment by MiguelCastillo** [comment]
Yeah we want to keep the current behavior, we just want to make it more correct.  So checking for empty string and ensuring the input is a string is what we want.  Or are you thinking of a use case where we want to accept empty strings?

**Comment by Mark-Simulacrum** [comment]
I don't think accepting empty strings at this point is a required/wanted. If we want to do that in the future, we can always change the if statement.

**Comment by MiguelCastillo** [comment]
This issue does not apply anymore.
